190901-1103/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('admincp');
});
Auth::routes();

#======================================= Admin Area ===========================================
#==============================================================================================

# ========== admin Auth Area ==============================================
Route::get('admincp/login','Admin\LoginController@showLoginForm');
Route::post('admincp/login','Admin\LoginController@login')->name('admin.login');
Route::post('admincp/password/email','Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::post('admincp/password/reset','Admin\ResetPasswordController@reset')->name('admin.password.update');
Route::get('admincp/password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::get('admincp/password/reset/{token}','Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
# =====================================================================

Route::group(['prefix' => 'admincp', 'middleware' => ['admin','auth:admin']], function () {

    Route::get('logout','Admin\LoginController@logout')->name('admin.logout');

    Route::get('/', function () {
        return view('admin.home.index');
    });

    // first controller to test standard pages
    Route::resource('testArea', 'Admin\FirstController');
    Route::get('testArea/{id}/delete', 'Admin\FirstController@destroy');

    #============================ Roles Area =================================
    Route::resource('roles', 'RoleController');
    Route::get('roles/users/{roleName}', 'RoleController@UsersHasRole');

    #============================ Users Area =================================
    Route::resource('users', 'UserController');

    #=========================== Site Settings Area ==================================
    Route::resource('settings','Admin\settingController');

    Route::resource('products','Admin\ProductController');

    Route::resource('blogs','Admin\BlogController');

    Route::resource('disbates','Admin\Blog1Controller');

    Route::resource('catogeries','Admin\CatogeryController');

    Route::resource('medicines','Admin\MedicineController');

    Route::resource('settings','Admin\SettingsController');

    Route::resource('contact_us','Admin\ContactusController');

    Route::resource('user','Admin\UserController');

    Route::resource('measurements','Admin\MeasurmentController');

    Route::resource('sugers','Admin\TypesugerController');

    Route::resource('pages','Admin\PagesController');

    Route::resource('admins','Admin\AdminController');

    Route::resource('reading','Admin\ReadingController');

    Route::resource('statistics','Admin\StatisticsController');

    Route::resource('admincp','Admin\StatisticsController');

    Route::resource('account_status','Admin\Account_statusController');

    Route::resource('messagers','Admin\MessagerController');

    Route::resource('chart', 'Admin\ChartContoller');

});

Route::get('testtt', function () {
    return view('admin.testt');
});

190901-1103/app/Models/Catogery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Catogery extends Model 
{

    protected $table = 'catogeries';
    public $timestamps = true;
    protected $fillable = array('name', 'image');

    public function products()
    {
        return $this->hasMany('App\Product');
    }

}

190901-1103/app/Http/Controllers/Admin/Api/CatogeryController.php
<?php

namespace App\Http\Controllers\Admin\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CatogeryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

190901-1103/app/Http/Controllers/Admin/CatogeryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Catogery;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;

class CatogeryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $cats=  Catogery::all();
       //dd($cats);
       return view('admin.catogery.index',compact('cats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       
        return view('admin.catogery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $rule=[
           'name.ar'=>'required|max:191',
           'name.en'=>'required|max:191',
            'image'=>'required|mimes:png',
       ];
       
       $message=[
           'name.requied'=>'this is required',
           'image.required'=>'image field is required'
       ];
       
       $this->validate($request,$rule,$message);


       $data = [
           'name'=> json_encode($request->name, JSON_UNESCAPED_UNICODE)
       ];

        if($request->hasFile('image')){
            $thumbnail = $request->file('image');
            $filename = time() . '.' . $thumbnail->getClientOriginalExtension();
            Image::make($thumbnail)->resize(300, 300)->save( public_path('/uploads/' . $filename ) );
            $data['image'] = $filename;
        };

        $cat=Catogery::create($data);

        flash()->message('تم إضافة القسم بنجاح');
          
     return redirect(route('catogeries.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cat=Catogery::find($id);


        
        return view('admin.catogery.edit',compact('cat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          $cat=Catogery::find($id);
          $cat->update([
              'name'=> json_encode($request->name, JSON_UNESCAPED_UNICODE)
                       ]);


        if($request->hasFile('image')){
            $thumbnail = $request->file('image');
            $filename = time() . '.' . $thumbnail->getClientOriginalExtension();
            Image::make($thumbnail)->resize(200, 200)->save( public_path('/uploads/' . $filename ) );
            $cat->image = $filename;
            $cat->save();
        };


        flash()->message('تم تعديل القسم بنجاح');
           
           return redirect(route('catogeries.index'));
          
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cat=Catogery::find($id);
        $cat->delete();
         flash()->message('تم حذف القسم بنجاح');
        return back();
    }
}

190901-1103/app/Http/Controllers/Api/CatogeryController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Catogery;

use App\Http\Resources\CatogeryResource;
use Illuminate\Support\Facades\Auth;

class CatogeryController extends Controller
{
    use apiResponseTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $user = Auth::user();

        $cat=Catogery::all();

        $cats= CatogeryResource::collection($cat);

        return $this->apiResponse($cats);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

190901-1103/resources/views/admin/catogery/create.blade.php
@extends('admin.layouts.app')
@inject('model','App\Models\Catogery')
@section('title')

@endsection
@section('topBar')
	<li class="m-menu__item">
		<a href="{{url('admincp')}}" class="m-menu__link">
			<span class="m-menu__link-text">الرئيسية</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item">
		<a href="{{url('admincp/users')}}" class="m-menu__link">
			<span class="m-menu__link-text">التحكم بالاقسام</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item" style="background: #e0deff;">
		<a href="javascript:;" class="m-menu__link">
			<span class="m-menu__link-text"></span>
			<i class="m-menu__hor-arrow la la-angle-down"></i>
		</a>
	</li>
@endsection

@section('header')
@endsection

@section('content')
	<!--begin::Portlet-->
	<div class="m-portlet">
		<div class="m-portlet__head">
			<div class="m-portlet__head-caption">
				<div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
					<h3 class="m-portlet__head-text">

					</h3>
				</div>
			</div>
		</div>
		
		
				<pre>
@include('error.error')
		</pre>


	{!!Form::model($model,[
'action'=>'Admin\CatogeryController@store',
'files'=>true,
'class'=>'m-form m-form--fit m-form--label-align-right'
]) !!}



			<div class="col-lg-12">
			<label class=" col-form-label">   اسم التصنيف عربي</label>

			<div class="col-lg-9">


			{!!Form::text('name[ar]',null,[
            'class'=>'form-control m-input','placeholder'=>" اسم التصنيف عربي"
            ])!!}
			</div>
			</div>


		<div class="col-lg-12">
			<label class=" col-form-label">   اسم التصنيف انجليزي</label>

			<div class="col-lg-9">


				{!!Form::text('name[en]',null,[
                'class'=>'form-control m-input','placeholder'=>" اسم التصنيف انجليزي"
                ])!!}
			</div>
		</div>




		<div class="col-lg-12">
				<label class="col-lg-1 col-form-label"> الصوره</label>


				<div class="col-lg-9">
					{!!Form::file('image',null,[
                'class'=>'form-control m-input'
                ])!!}
		</div>
			</div>
<br><br>
			<br>
			<div class='form-group' >
				<br>
				<button class="btn btn-primary" type="submit"> تسجيل</button>
			</div>

		</div>




		{!! Form::close()!!}
	<!--end::Form-->
	</div>
	<!--end::Portlet-->
@endsection
@section('footer')
<script type="text/javascript">

</script>
@endsection

190901-1103/resources/views/admin/catogery/edit.blade.php
@extends('admin.layouts.app')

@section('title')
	تعديل : الاقسام
@endsection
@section('topBar')
	<li class="m-menu__item">
		<a href="{{url('admincp')}}" class="m-menu__link">
			<span class="m-menu__link-text">الرئيسية</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item">
		<a href="{{url('admincp/catogeries')}}" class="m-menu__link">
			<span class="m-menu__link-text">التحكم بالاقسام</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item" style="background: #e0deff;">
		<a href="javascript:;" class="m-menu__link">
			<span class="m-menu__link-text">الاقسام</span>
			<i class="m-menu__hor-arrow la la-angle-down"></i>
		</a>
	</li>
@endsection

@section('header')
@endsection

@section('content')
	<!--begin::Portlet-->
	<div class="m-portlet">
		<div class="m-portlet__head">
			<div class="m-portlet__head-caption">
				<div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
					<h3 class="m-portlet__head-text">
						تعديل لالاقسام
					</h3>
				</div>
			</div>
		</div>

	{!!Form::model($cat,[
'action'=>['Admin\CatogeryController@update',$cat->id],
'method'=>'put',
'files'=>true,
'class'=>'m-form m-form--fit m-form--label-align-right'
]) !!}



			<div class="col-lg-12">
			<label class="col-form-label">اسم التصنيف عربي</label>

			<div class="col-lg-9">


			{!!Form::text('name[ar]',getJsonData($cat->name,'ar'),[
            'class'=>'form-control m-input','placeholder'=>"اسم التصنيف عربي"
            ])!!}
			</div>
			</div>



		<div class="col-lg-12">
			<label class=" col-form-label">اسم التصنيف انجليزي</label>

			<div class="col-lg-9">


				{!!Form::text('name[en]',getJsonData($cat->name,'en'),[
                'class'=>'form-control m-input','placeholder'=>"اسم التصنيف انجليزي"
                ])!!}
			</div>
		</div>





			<div class="col-lg-12">
				<label class="col-lg-1 col-form-label"> الصوره</label>


				<div class="col-lg-9">
					{!!Form::file('image',null,[
                'class'=>'form-control m-input'
                ])!!}
				</div>
			</div>
<br><br>
			<br>
			<div class='form-group' >
				<br>
				<button class="btn btn-primary" type="submit"> تعديل</button>
			</div>

		</div>




		{!! Form::close()!!}
	<!--end::Form-->
	</div>
	<!--end::Portlet-->
@endsection
@section('footer')
<script type="text/javascript">

</script>
@endsection

190901-1103/resources/views/admin/catogery/index.blade.php
@extends('admin.layouts.app')

@section('title')
	عرض الاقسام
@endsection
@section('topBar')
	<li class="m-menu__item">
		<a href="{{url('admincp')}}" class="m-menu__link">
			<span class="m-menu__link-text">الرئيسية</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item" style="background: #e0deff;">
		<a href="javascript:;" class="m-menu__link">
			<span class="m-menu__link-text">التحكم بالاقسام</span>
			<i class="m-menu__hor-arrow la la-angle-down"></i>
		</a>
	</li>
@endsection
@section('header')
	<!--begin::Page Vendors Styles -->
	{!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
	<!--end::Page Vendors Styles -->
@endsection

@section('content')
	<!-- END: Subheader -->
	<div class="m-content">
		<div class="m-portlet m-portlet--mobile">
			<div class="m-portlet__head">
				<div class="m-portlet__head-caption">
					<div class="m-portlet__head-title">
						<h3 class="m-portlet__head-text">التحكم بالاقسام
						</h3>
					</div>
				</div>
			</div>
		</div>
			<div class="m-portlet__body">


		<div >
			<a href="{{url(route('catogeries.create'))}}" class="btn btn_primary btn btn-danger" ><i class=" fa fa-edit"></i>اضافه جديد</a>
			<br><br> @include('error.error')
		@if($cats->count())
			@include('flash::message')
			<!--begin: Datatable -->
				<table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_users">
					<thead>
					<tr >
						<th>#</th>
						<th>اسم التصنيف </th>
						<th>الوقت</th>
						<th>الصوره</th>
						<th>تعديل </th>
						<th>حذف</th>
					</tr>
					</thead>
					<tbody>
					@foreach($cats as $cat)
						<tr class="debTr">
							<th>{{$cat->id}}</th>
							<th>{{getJsonData($cat->name,'ar')}}</th>
							<th>{{$cat->created_at}}</th>

							<th> <img src="{{asset('/uploads/' . $cat->image)}}" style="width:200px; height:100px"></th>
							<th>
								<a href="{{url('admincp/catogeries/'.$cat->id.'/edit')}}" class="btn btn-brand m-btn editDeps">تعديل</a>

							</th>
							<th>
								<div class="form-group">


									{!! Form::open([

                                  'action'=>['Admin\CatogeryController@destroy',$cat->id],
                                  'method'=>'delete'
                              ]) !!}

									<button class="btn btn-danger">حذف</button>

									{!! Form::close() !!}


								</div>

							</th>
						</tr>
					@endforeach
					</tbody>
				</table>

		</div>

	<!-- END EXAMPLE TABLE PORTLET-->
	</div>
	@else

		<div class="alert alert-danger">
			no data
		</div>
		@endif
		</div>

</div></div>
	</div>





@endsection
@section('footer')
	<!--begin::Page Vendors -->
	{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}
	{!! Html::script('admin/custom/js/countries.js') !!}
	<!--end::Page Vendors -->
<script type="text/javascript">
	var table = $('#m_table_users');
	// begin first table
	table.DataTable({
      	language: {
      	    aria: {
      	        sortAscending: ": ترتيب تصاعدى",
      	        sortDescending: ": ترتيب تنازلى"
      	    },
      	    emptyTable: "لا توجد اى بيانات متاحه",
      	    info: "إظهار _START_ إلى _END_ من _TOTAL_ حقل",
      	    infoEmpty: "لا توجد حقول",
      	    infoFiltered: "( الإجمالى _MAX_ حقل )",
      	    lengthMenu: "عدد الحقول : _MENU_",
      	    search: " بحث بإسم المستخدم :",
      	    zeroRecords: "لا توجد نتائج "
      	},

		responsive: true,
		order: [[0, "desc"]],
        lengthMenu: [[10, 20, 30, 50, -1], [10, 20, 30, 50, "الكل"]],
        pageLength: 10,
      	columnDefs: [{ "targets": [0,2,3,4], "searchable": false },{ "targets": [4], "orderable": false }]
	});


	$(document).on("click",".delUser",function(e) {
		e.preventDefault();
		var url = $(this).attr("href"),
		userId = $(this).data('id'),
		pData = {
			_token : "{{csrf_token()}}",
			_method : "delete"
		},
		ths = $(this);
		$.post(url,pData,function(data){
			toastrNotifyResponse(data);
			if(data.success){
				ths.closest('tr').remove();
			}
		});
	});
</script>
@endsection
	